// Application State
let state = {
    theme: 'light',
    lang: 'ms',
    currentView: 'student', // 'student' or 'counselor'
    counselors: [], // Dynamic counselor list
    appointments: [],
    selectedDate: null,
    selectedTimeSlot: null,
    currentMonth: new Date().getMonth(),
    currentYear: new Date().getFullYear(),
    availabilityMonth: new Date().getMonth(),
    availabilityYear: new Date().getFullYear(),
    unavailableDates: {},
    availabilitySlots: {},
    selectedAvailabilityDate: null,
    minNoticeHours: 24,
    counselorLoggedIn: false,
    currentCounselorId: null,
    authSelectedCounselorId: null
};

// Available time slots configuration
const TIME_SLOTS = [
    "09:00 AM",
    "10:00 AM",
    "11:00 AM",
    "12:00 PM",
    "02:00 PM",
    "03:00 PM",
    "04:00 PM"
];

const TRANSLATIONS = {
    ms: {
        "document.title": "Sistem Pengurusan Rujukan dan Temujanji Kaunseling - TVETMARA Besut",
        "document.description": "Sistem Pengurusan Rujukan dan Temujanji Kaunseling TVETMARA Besut untuk rujukan pensyarah/staf, tempahan sulit pelajar dan pengurusan kes kaunselor.",
        "brand.title": "Unit Kaunseling dan Kerjaya",
        "nav.home": "Utama",
        "nav.counselors": "Kaunselor",
        "nav.booking": "Rujukan / Tempahan",
        "nav.resources": "Sumber",
        "nav.portal": "Portal Kaunselor",
        "portal.student": "Portal Pelajar",
        "language.aria": "Pilihan bahasa",
        "theme.aria": "Tukar tema",
        "menu.aria": "Buka menu navigasi",
        "backTop.aria": "Kembali ke atas",
        "hero.badge": "Rujukan Kes • Tempahan Sulit • Pengurusan Kaunselor",
        "hero.title": "Sistem Pengurusan <span class=\"gradient-text\">Rujukan Kaunseling</span>",
        "hero.description": "Satu sistem untuk rujukan kes oleh pensyarah/staf, tempahan sulit pelajar dan pengurusan temujanji oleh kaunselor TVETMARA Besut.",
        "hero.primaryCta": "Buat Rujukan Kes",
        "hero.secondaryCta": "Tempahan Sulit Pelajar",
        "hero.statConfidential": "Rujukan Pensyarah / Staf",
        "hero.statConfidentialText": "Salurkan kes pelajar kepada unit kaunseling",
        "hero.statResponse": "Tempahan Kendiri Sulit",
        "hero.statResponseText": "Pelajar boleh mohon tanpa makluman pensyarah/staf",
        "hero.statOnline": "Dashboard Kaunselor",
        "hero.statOnlineText": "Urus kes, status dan jadual sesi",
        "hero.flowReferral": "Rujukan Pensyarah / Staf",
        "hero.flowReferralText": "Salurkan kes pelajar kepada unit kaunseling",
        "hero.flowSelf": "Tempahan Kendiri Sulit",
        "hero.flowSelfText": "Pelajar boleh mohon tanpa makluman pensyarah/staf",
        "hero.flowDashboard": "Dashboard Kaunselor",
        "hero.flowDashboardText": "Urus kes, status dan jadual sesi",
        "hero.referralKicker": "Untuk Pensyarah / Staf",
        "hero.referralCardTitle": "Hantar Rujukan Pelajar",
        "hero.referralCardDesc": "Rujuk pelajar yang memerlukan sokongan kaunseling dengan sebab rujukan dan maklumat sokongan.",
        "hero.selfKicker": "Untuk Pelajar",
        "hero.selfCardTitle": "Tempahan Kendiri Sulit",
        "hero.selfCardDesc": "Pelajar boleh memohon sesi kaunseling secara terus dan sulit tanpa makluman pihak lain.",
        "hero.trustNote": "Maklumat adalah sulit dan hanya diakses oleh pihak Unit Kaunseling dan Kerjaya.",
        "hero.brandCard": "Unit Kaunseling dan Kerjaya",
        "hero.calendarMonth": "Julai 2026",
        "hero.availabilityTitle": "Slot Temujanji",
        "hero.availabilityLoading": "Menyemak ketersediaan...",
        "hero.availabilityEmpty": "Tiada slot terdekat tersedia. Sila semak bahagian tempahan.",
        "hero.availableSlots": "{count} slot",
        "hero.viewAllSlots": "Lihat Semua Slot",
        "hero.quote": "\"Anda tidak perlu menghadapi semuanya seorang diri.\"",
        "hero.quoteBy": "- Unit Kaunseling dan Kerjaya",
        "hero.quotes": [
            "\"Anda tidak perlu menghadapi semuanya seorang diri.\"",
            "\"Langkah kecil hari ini boleh membuka ruang yang lebih tenang esok.\"",
            "\"Meminta bantuan ialah tanda anda sedang menjaga diri.\""
        ],
        "counselors.subtitle": "Pasukan Kami",
        "counselors.title": "Kaunselor Unit Kaunseling dan Kerjaya",
        "counselors.description": "Pegawai yang bersedia mendengar, membimbing dan menyokong perjalanan pembelajaran serta kerjaya pelajar TVETMARA Besut.",
        "services.title": "Bidang Sokongan Kaunseling",
        "services.description": "Rujukan dan tempahan boleh melibatkan sokongan akademik, kerjaya, emosi dan kebajikan pelajar.",
        "services.academicTitle": "Sokongan Akademik",
        "services.academicDesc": "Bimbingan pembelajaran, motivasi dan pengurusan tekanan akademik.",
        "services.careerTitle": "Bimbingan Kerjaya",
        "services.careerDesc": "Perancangan kerjaya, peluang pekerjaan dan pembangunan diri.",
        "services.emotionTitle": "Kesihatan Emosi",
        "services.emotionDesc": "Sokongan untuk tekanan, emosi, keyakinan diri dan kesejahteraan.",
        "services.welfareTitle": "Kebajikan Pelajar",
        "services.welfareDesc": "Bantuan kebajikan, kewangan dan hal-hal peribadi pelajar.",
        "services.learnMore": "Ketahui lanjut",
        "services.duration45": "45-60 minit",
        "services.duration30": "30-45 minit",
        "services.academicSuitable": "Isu pembelajaran",
        "services.careerSuitable": "Perancangan kerjaya",
        "services.emotionSuitable": "Sokongan emosi",
        "services.welfareSuitable": "Isu kebajikan",
        "process.referralTitle": "Rujukan Pensyarah / Staf",
        "process.referral1": "Hantar rujukan",
        "process.referral2": "Kaunselor menyemak",
        "process.referral3": "Sesi dijadualkan",
        "process.referral4": "Tindakan susulan",
        "process.selfTitle": "Tempahan Kendiri Sulit",
        "process.self1": "Isi maklumat",
        "process.self2": "Pilih slot",
        "process.self3": "Kaunselor sahkan",
        "process.self4": "Sesi dijalankan",
        "serviceModal.close": "Tutup maklumat perkhidmatan",
        "serviceModal.eyebrow": "Perkhidmatan",
        "serviceModal.duration": "Tempoh sesi",
        "serviceModal.suitable": "Sesuai untuk",
        "serviceModal.focusTitle": "Fokus sesi",
        "serviceModal.book": "Tempah sesi ini",
        "serviceDetail.Academic.desc": "Sesi untuk membantu pelajar mengurus cabaran akademik, motivasi belajar, penyesuaian kursus dan tekanan pembelajaran.",
        "serviceDetail.Academic.suitable": "Pelajar yang menghadapi isu pembelajaran, motivasi, tugasan atau penyesuaian akademik.",
        "serviceDetail.Academic.focus": ["Kenal pasti cabaran akademik", "Bina strategi belajar yang realistik", "Rancang langkah susulan bersama kaunselor"],
        "serviceDetail.Career.desc": "Sesi untuk membimbing pelajar membuat keputusan kerjaya, latihan industri, persediaan temuduga dan hala tuju selepas tamat pengajian.",
        "serviceDetail.Career.suitable": "Pelajar yang sedang merancang latihan industri, pekerjaan, resume atau hala tuju kerjaya.",
        "serviceDetail.Career.focus": ["Teroka minat dan kekuatan diri", "Rancang laluan latihan industri atau pekerjaan", "Semak persediaan resume dan temuduga"],
        "serviceDetail.Personal.desc": "Sesi sokongan awal untuk pelajar yang berdepan tekanan, konflik, kebimbangan, keyakinan diri atau isu emosi harian.",
        "serviceDetail.Personal.suitable": "Pelajar yang perlukan ruang selamat untuk bercakap dan menyusun semula keadaan diri.",
        "serviceDetail.Personal.focus": ["Dengar dan fahami situasi pelajar", "Kenal pasti sokongan yang sesuai", "Bina langkah kecil untuk kesejahteraan diri"],
        "serviceDetail.Financial.desc": "Sesi untuk membincangkan isu kebajikan pelajar, kewangan, elaun, sokongan kampus dan rujukan bantuan yang sesuai.",
        "serviceDetail.Financial.suitable": "Pelajar yang memerlukan panduan berkaitan kebajikan, kewangan atau sokongan kampus.",
        "serviceDetail.Financial.focus": ["Kenal pasti isu kebajikan utama", "Semak saluran bantuan yang sesuai", "Rancang tindakan atau rujukan seterusnya"],
        "booking.subtitle": "Rujukan & Temujanji",
        "booking.title": "Sistem Pengurusan Rujukan dan Temujanji Kaunseling",
        "booking.description": "Mulakan dengan rujukan pensyarah/staf atau tempahan kendiri yang sulit. Kalendar akan memaparkan slot berdasarkan kaunselor yang dipilih.",
        "booking.step1": "1. Maklumat Permohonan",
        "booking.step2": "2. Pilih Tarikh & Masa",
        "booking.guideTitle": "Cara guna sistem",
        "booking.guideStep1": "Pilih jenis permohonan: rujukan pensyarah/staf atau tempahan kendiri sulit.",
        "booking.guideStep2": "Pilih kaunselor dahulu supaya kalendar hanya memaparkan slot yang tersedia untuk kaunselor tersebut.",
        "booking.guideStep3": "Kaunselor akan menyemak kes, menetapkan sesi individu atau berkelompok, dan memaklumkan status kepada pelajar.",
        "booking.slotTitle": "Pilih Slot Masa",
        "booking.selectDatePrompt": "Sila pilih tarikh yang sah dahulu.",
        "booking.chooseCounselorFirst": "Sila pilih kaunselor pilihan dahulu untuk semak tarikh dan slot yang tersedia.",
        "booking.noSelection": "Belum ada tarikh/masa dipilih.",
        "statusChecker.title": "Semak Status Tempahan",
        "statusChecker.desc": "Masukkan rujukan tiket dan nombor pelajar untuk semak sama ada tempahan masih menunggu, diluluskan, dibatalkan atau dijadualkan semula.",
        "statusChecker.ticket": "Rujukan Tiket",
        "statusChecker.ticketPlaceholder": "cth. T-1234",
        "statusChecker.studentId": "No. Pelajar",
        "statusChecker.studentIdPlaceholder": "cth. DFK230717",
        "statusChecker.button": "Semak Status",
        "statusChecker.notFound": "Tiada tempahan ditemui. Sila semak semula rujukan tiket dan nombor pelajar.",
        "statusChecker.foundTitle": "Status tempahan anda",
        "statusChecker.note": "Sila semak status ini dari semasa ke semasa. Untuk sistem sebenar, notifikasi automatik melalui e-mel/WhatsApp boleh disambungkan apabila pangkalan data telah dibuat.",
        "statusChecker.status": "Status",
        "statusChecker.requestType": "Jenis Permohonan",
        "statusChecker.dateTime": "Tarikh & Masa",
        "statusChecker.counselor": "Kaunselor",
        "statusChecker.type": "Jenis Sesi",
        "calendar.prev": "Bulan sebelumnya",
        "calendar.next": "Bulan seterusnya",
        "calendar.sun": "Aha",
        "calendar.mon": "Isn",
        "calendar.tue": "Sel",
        "calendar.wed": "Rab",
        "calendar.thu": "Kha",
        "calendar.fri": "Jum",
        "calendar.sat": "Sab",
        "calendar.available": "Tersedia",
        "calendar.selected": "Dipilih",
        "calendar.unavailable": "Tidak tersedia",
        "form.fullName": "Nama Penuh <span class=\"required\">*</span>",
        "form.fullNamePlaceholder": "cth. Aqilah Husna",
        "form.requestType": "Jenis Permohonan",
        "form.requestSelf": "Tempahan Kendiri Sulit",
        "form.requestReferral": "Rujukan Pensyarah / Staf",
        "form.referralFirstNote": "Rujukan pensyarah/staf ialah aliran utama. Pelajar masih boleh memilih tempahan kendiri yang sulit.",
        "form.selfPrivacyNote": "Tempahan kendiri pelajar adalah sulit. Pensyarah, ketua program atau staf lain tidak akan dimaklumkan melalui sistem demo ini.",
        "form.stepApplicant": "Jenis & pemohon",
        "form.stepStudent": "Maklumat pelajar",
        "form.stepSession": "Sesi & slot",
        "form.stepSubmit": "Hantar",
        "form.studentId": "No. Pelajar <span class=\"required\">*</span>",
        "form.studentIdPlaceholder": "cth. IKM240199",
        "form.preferredCounselor": "Kaunselor Pilihan <span class=\"required\">*</span>",
        "form.program": "Program / Kursus <span class=\"required\">*</span>",
        "form.selectProgram": "Pilih program / kursus",
        "form.programPlaceholder": "cth. Diploma Teknologi Maklumat",
        "form.semester": "Semester <span class=\"required\">*</span>",
        "form.selectSem": "Pilih Semester",
        "form.sem1": "Semester 1",
        "form.sem2": "Semester 2",
        "form.sem3": "Semester 3",
        "form.sem4": "Semester 4",
        "form.sem5": "Semester 5",
        "form.sem6": "Semester 6",
        "form.phone": "No. Telefon <span class=\"required\">*</span>",
        "form.phonePlaceholder": "cth. 0123456789",
        "form.sessionType": "Jenis Konsultasi <span class=\"required\">*</span>",
        "form.selectConcern": "Pilih bidang bantuan",
        "form.reason": "Nyatakan Ringkas Keperluan Anda (Pilihan)",
        "form.reasonPlaceholder": "Tulis secara ringkas perkara yang ingin dibincangkan. Maklumat adalah sulit.",
        "form.referralInfo": "Maklumat Rujukan",
        "form.referrerName": "Nama Perujuk <span class=\"required\">*</span>",
        "form.referrerNamePlaceholder": "cth. Puan Siti Aminah",
        "form.referrerPosition": "Jawatan Perujuk <span class=\"required\">*</span>",
        "form.referrerPositionPlaceholder": "cth. Pensyarah / Pegawai HEP / Warden",
        "form.referrerDepartment": "Jabatan / Program <span class=\"required\">*</span>",
        "form.referrerDepartmentPlaceholder": "cth. DFK / HEP / Asrama",
        "form.referralSource": "Kategori Rujukan <span class=\"required\">*</span>",
        "form.selectReferralSource": "Pilih kategori rujukan",
        "form.referralSessionMode": "Cadangan Jenis Sesi (Pilihan)",
        "form.selectSessionMode": "Pilih jenis sesi",
        "form.counselorDecides": "Kaunselor tentukan",
        "form.referralPriority": "Tahap Keutamaan <span class=\"required\">*</span>",
        "form.referralReason": "Sebab Rujukan <span class=\"required\">*</span>",
        "form.referralReasonPlaceholder": "Nyatakan sebab rujukan secara ringkas.",
        "form.referralAttachment": "Lampiran Bahan",
        "form.attachmentHint": "Lampiran disimpan sebagai nama fail untuk demo ini.",
        "form.submit": "Hantar Permohonan Temujanji",
        "sessionType.Academic": "Kaunseling Akademik",
        "sessionType.Career": "Bimbingan Kerjaya & Kebolehpasaran",
        "sessionType.Personal": "Sokongan Peribadi / Emosi",
        "sessionType.Financial": "Bantuan Kewangan & Kebajikan",
        "sessionType.Other": "Kaunseling Lain",
        "requestType.self": "Kendiri",
        "requestType.referral": "Rujukan",
        "referralSource.Lecturer": "Rujukan Pensyarah",
        "referralSource.HEP": "Rujukan HEP",
        "referralSource.Warden": "Rujukan Warden",
        "sessionMode.PendingDecision": "Kaunselor tentukan",
        "sessionMode.Individual": "Individu",
        "sessionMode.Group": "Berkelompok",
        "priority.Normal": "Biasa",
        "priority.Urgent": "Segera",
        "resources.subtitle": "Sokongan Tambahan",
        "resources.title": "Soalan Lazim & Sumber",
        "resources.description": "Maklumat ringkas dan panduan awal untuk membantu pelajar sebelum atau selepas sesi kaunseling.",
        "faq.title": "Soalan Lazim",
        "faq.q1": "Adakah maklumat saya dirahsiakan?",
        "faq.a1": "Ya. Semua topik perbincangan, catatan peribadi dan maklumat yang dikongsi dalam sesi kaunseling adalah sulit, kecuali jika terdapat risiko keselamatan kepada diri sendiri atau orang lain.",
        "faq.q2": "Berapa lama tempoh setiap sesi?",
        "faq.a2": "Kebiasaannya sesi mengambil masa 45 hingga 60 minit. Tempoh boleh disesuaikan mengikut keperluan dan situasi anda.",
        "faq.q3": "Apa yang perlu dibuat jika berlaku kecemasan?",
        "faq.a3": "Jika anda atau rakan berada dalam krisis segera, hubungi warden kampus, Talian Kasih 15999, atau datang terus ke pejabat Unit Kaunseling dan Kerjaya semasa waktu operasi.",
        "resources.guidesTitle": "Panduan Kesihatan Mental & TVET",
        "resources.stressTitle": "Panduan Mengurus Stres Pelajar TVET",
        "resources.stressDesc": "Teknik ringkas untuk mengimbangi bengkel amali, tugasan dan akademik.",
        "resources.careerTitle": "Senarai Semak Persediaan Kerjaya",
        "resources.careerDesc": "Sediakan resume, latihan temuduga dan carian latihan industri.",
        "resources.mindTitle": "Latihan Pernafasan 10 Minit",
        "resources.mindDesc": "Amalan ringkas untuk menenangkan diri sebelum penilaian atau pembentangan.",
        "dashboard.title": "Dashboard Pengurusan Kes Kaunselor",
        "dashboard.subtitle": "Semak rujukan, sahkan temujanji, tetapkan sesi individu/berkelompok dan urus ketersediaan sendiri.",
        "dashboard.adminMode": "AKAUN KAUNSELOR",
        "dashboard.exit": "Keluar Portal",
        "dashboard.total": "Jumlah Tempahan",
        "dashboard.pending": "Menunggu Semakan",
        "dashboard.approved": "Temujanji Diluluskan",
        "dashboard.referralCases": "Kes Rujukan",
        "dashboard.selfBookings": "Tempahan Sulit",
        "dashboard.appointments": "Senarai Temujanji",
        "dashboard.generalAppointments": "Senarai Umum Tempahan Pelajar",
        "dashboard.generalAppointmentsDesc": "Paparan ringkas semua tempahan untuk rujukan bersama. Tindakan hanya boleh dibuat dalam senarai temujanji akaun sendiri.",
        "dashboard.allStatus": "Semua Status",
        "dashboard.newBookingAlert": "{count} tempahan baharu / menunggu memerlukan semakan anda.",
        "dashboard.noNewBookingAlert": "Tiada tempahan baharu yang menunggu semakan buat masa ini.",
        "dashboard.downloadTitle": "Muat turun data tempahan",
        "dashboard.downloadDesc": "Simpan salinan data tempahan sebagai CSV untuk rekod unit.",
        "dashboard.sessionDecision": "Keputusan sesi",
        "download.myClients": "Muat Turun Klien Saya",
        "download.allBookings": "Muat Turun Semua Tempahan",
        "download.empty": "Tiada data tempahan untuk dimuat turun.",
        "availability.title": "Ketersediaan Kaunselor",
        "availability.description": "Urus tarikh dan slot masa anda sendiri. Pelajar hanya akan nampak masa yang anda buka untuk sesi.",
        "availability.counselor": "Kaunselor",
        "availability.minNotice": "Notis Minimum Sebelum Sesi (jam)",
        "availability.minNoticeHint": "Contoh: 24 jam bermaksud pelajar tidak boleh tempah slot terlalu mengejut seperti pagi ini untuk sesi hari yang sama.",
        "availability.prev": "Bulan sebelumnya",
        "availability.next": "Bulan seterusnya",
        "availability.available": "Boleh sesi",
        "availability.unavailable": "Tidak boleh sesi",
        "availability.saved": "Tetapan ketersediaan disimpan.",
        "availability.noCounselor": "Sila tambah kaunselor dahulu sebelum menetapkan ketersediaan.",
        "availability.profileTitle": "Akaun sedang log masuk",
        "availability.slotTitle": "Slot masa untuk tarikh dipilih",
        "availability.selectDate": "Klik satu tarikh pada kalendar untuk urus slot masa.",
        "availability.noDate": "Tiada tarikh dipilih",
        "availability.openAll": "Buka semua slot",
        "availability.closeAll": "Tutup semua slot",
        "availability.defaultSlots": "Semua slot dibuka secara lalai.",
        "availability.visibleToStudents": "Slot ini boleh dilihat oleh pelajar.",
        "availability.tooSoon": "Slot dibuka, tetapi belum boleh ditempah oleh pelajar kerana notis minimum.",
        "availability.bookedSlot": "Slot ini sudah mempunyai temujanji diluluskan.",
        "availability.closedSlot": "Slot ini ditutup oleh kaunselor.",
        "availability.openShort": "Dibuka",
        "availability.tooSoonShort": "Terlalu awal",
        "availability.bookedShort": "Ditempah",
        "availability.closedShort": "Tutup",
        "booking.noSlots": "Tiada slot tersedia untuk tarikh ini. Sila pilih tarikh lain atau kaunselor lain.",
        "table.dateTime": "Tarikh & Masa",
        "table.student": "Maklumat Pelajar",
        "table.counselor": "Kaunselor",
        "table.typeReason": "Jenis & Sebab",
        "table.status": "Status",
        "table.actions": "Tindakan",
        "directory.title": "Pengurusan Direktori Kaunselor",
        "directory.active": "Kaunselor / Pelatih Aktif",
        "directory.addProfile": "Tambah Profil Baharu",
        "directory.fullName": "Nama Penuh <span class=\"required\">*</span>",
        "directory.fullNamePlaceholder": "cth. Cik Nor Shazwani binti Rosli",
        "directory.role": "Peranan / Kelayakan <span class=\"required\">*</span>",
        "directory.rolePlaceholder": "cth. Kaunselor Pelatih Berdaftar (KB, PA)",
        "directory.badge": "Label Lencana <span class=\"required\">*</span>",
        "directory.badgePlaceholder": "cth. Kaunselor Pelatih",
        "directory.specialties": "Kepakaran (asingkan dengan koma) <span class=\"required\">*</span>",
        "directory.specialtiesPlaceholder": "cth. Stres Peperiksaan, Motivasi Belajar, Hala Tuju Kerjaya",
        "directory.scopes": "Skop Tugas / Perkhidmatan (asingkan dengan koma) <span class=\"required\">*</span>",
        "directory.scopesPlaceholder": "cth. Kaunseling Individu, Kaunseling Kelompok, Akademik",
        "directory.bio": "Biografi Ringkas <span class=\"required\">*</span>",
        "directory.bioPlaceholder": "Nyatakan kelayakan, bidang kepakaran dan latar belakang kaunselor...",
        "directory.submit": "Tambah Profil Kaunselor",
        "modal.successTitle": "Permohonan Temujanji Berjaya Dihantar",
        "modal.successDesc": "Terima kasih. Permohonan anda telah direkodkan dan sedang menunggu pengesahan kaunselor. Butiran sesi adalah seperti berikut:",
        "modal.done": "Selesai",
        "modal.print": "Cetak Tiket",
        "receipt.ticket": "Rujukan Tiket:",
        "receipt.student": "Nama Pelajar:",
        "receipt.dateTime": "Tarikh & Masa:",
        "receipt.counselor": "Kaunselor Bertugas:",
        "receipt.type": "Jenis Konsultasi:",
        "receipt.statusNote": "Status: Menunggu semakan. Dalam keadaan tertentu, sesi boleh dipindahkan kepada kaunselor lain dan anda akan dimaklumkan.",
        "receipt.saveReminder": "Sila simpan resit ini atau ambil screenshot. Gunakan nombor tiket untuk semak sama ada tempahan anda menunggu, diluluskan, dibatalkan atau dipindahkan kepada kaunselor lain.",
        "auth.title": "Pengesahan Portal Kaunselor",
        "auth.desc": "Pilih akaun kaunselor anda dan masukkan kata laluan untuk mengurus temujanji serta ketersediaan sendiri.",
        "auth.chooseAccount": "Pilih akaun kaunselor",
        "auth.password": "Kata Laluan",
        "auth.placeholder": "Masukkan kata laluan akaun",
        "auth.error": "Kata laluan tidak sah. Sila cuba lagi.",
        "auth.cancel": "Batal",
        "auth.signIn": "Log Masuk",
        "auth.showPassword": "Tunjuk kata laluan",
        "auth.hidePassword": "Sembunyikan kata laluan",
        "footer.brand": "Unit Kaunseling dan Kerjaya",
        "footer.desc": "Perkhidmatan kaunseling dan bimbingan kerjaya yang sulit, profesional dan mesra pelajar untuk warga TVETMARA Besut.",
        "footer.hoursTitle": "Waktu Operasi",
        "footer.hours1": "Ahad - Rabu: 8:00 pagi - 5:00 petang",
        "footer.hours2": "Khamis: 8:00 pagi - 3:30 petang",
        "footer.hours3": "Jumaat - Sabtu: Tutup",
        "footer.contactTitle": "Hubungi Kami",
        "footer.address": "Unit Kaunseling dan Kerjaya, IKM Besut",
        "footer.copy": "&copy; 2026 Unit Kaunseling dan Kerjaya, TVETMARA Besut. Hak cipta terpelihara.",
        "status.Pending": "Menunggu",
        "status.Approved": "Diluluskan",
        "status.Cancelled": "Dibatalkan",
        "select.chooseCounselor": "Pilih kaunselor",
        "select.allCounselors": "Semua Kaunselor",
        "counselor.noActiveTitle": "Tiada kaunselor aktif buat masa ini",
        "counselor.noActiveDesc": "Sila semak semula kemudian atau hubungi unit pentadbiran.",
        "counselor.bookSession": "Tempah Sesi",
        "directory.noActive": "Tiada kaunselor aktif didaftarkan.",
        "directory.deleteTitle": "Padam Profil Kaunselor",
        "directory.deleteConfirm": "Adakah anda pasti mahu memadam profil {name}? Profil ini akan dikeluarkan daripada direktori dan pilihan penjadualan slot.",
        "alerts.requiredFields": "Sila lengkapkan semua medan wajib.",
        "alerts.profileAdded": "Profil untuk {name} berjaya ditambah.",
        "alerts.selectDate": "Sila pilih tarikh dan slot masa yang tersedia.",
        "alerts.resourceStress": "Demo Sumber: Membuka panduan pengurusan stres.",
        "alerts.resourceCareer": "Demo Sumber: Membuka senarai semak kerjaya.",
        "alerts.resourceMindfulness": "Demo Sumber: Membuka latihan pernafasan.",
        "summary.selected": "Dipilih:",
        "summary.at": "pada",
        "booking.unassigned": "Belum ditetapkan",
        "table.noAppointments": "Tiada temujanji yang sepadan dengan penapis pilihan.",
        "table.noGeneralAppointments": "Belum ada tempahan pelajar untuk dipaparkan.",
        "table.ref": "Ruj",
        "table.referrer": "Perujuk",
        "table.unit": "Unit Kaunseling dan Kerjaya",
        "table.noDetails": "Tiada butiran diberikan",
        "action.approve": "Luluskan tempahan",
        "action.cancelDecline": "Batal / tolak tempahan",
        "action.reschedule": "Mohon jadual semula pelajar",
        "action.cancel": "Batalkan tempahan",
        "action.reopen": "Buka semula / set kepada menunggu",
        "action.transfer": "Pindahkan kepada kaunselor lain",
        "action.whatsapp": "Hantar notis WhatsApp",
        "reschedule.prompt": "Jadual semula tempahan Ruj: {ref} untuk {name}.\nMasukkan tarikh baharu (DD/MM/YY atau DD/MM/YYYY):",
        "reschedule.timePrompt": "Masukkan masa baharu. Pilihan: {slots}",
        "reschedule.invalidDate": "Format tarikh tidak sah. Gunakan DD/MM/YY atau DD/MM/YYYY.",
        "reschedule.invalidTime": "Masa tidak sah. Sila pilih salah satu slot yang tersedia.",
        "reschedule.success": "Jadual semula berjaya. Status dikembalikan kepada menunggu untuk semakan. Pelajar boleh semak perubahan melalui rujukan tiket pada bahagian Semak Status Tempahan.",
        "transfer.prompt": "Pindahkan tempahan Ruj: {ref} kepada kaunselor lain.\nPilihan:\n{options}\n\nMasukkan nombor pilihan:",
        "transfer.invalid": "Pilihan kaunselor tidak sah.",
        "transfer.success": "Tempahan dipindahkan dan ditetapkan kepada status menunggu untuk semakan kaunselor penerima.",
        "whatsapp.message": "Assalamualaikum {name}. Status tempahan kaunseling anda ({ref}) ialah: {status}. Tarikh/Masa: {date} {time}. Kaunselor: {counselor}. Sila simpan nombor tiket ini untuk semakan status di laman Unit Kaunseling dan Kerjaya TVETMARA Besut.",
        "whatsapp.noPhone": "Nombor telefon pelajar tidak tersedia.",
        months: ["Januari", "Februari", "Mac", "April", "Mei", "Jun", "Julai", "Ogos", "September", "Oktober", "November", "Disember"]
    },
    en: {
        "document.title": "Counseling Referral and Appointment Management System - TVETMARA Besut",
        "document.description": "TVETMARA Besut Counseling Referral and Appointment Management System for lecturer/staff referrals, confidential student self-booking, and counselor case management.",
        "brand.title": "Counseling and Career Unit",
        "nav.home": "Home",
        "nav.counselors": "Counselors",
        "nav.booking": "Referral / Booking",
        "nav.resources": "Resources",
        "nav.portal": "Counselor Portal",
        "portal.student": "Student Portal",
        "language.aria": "Language options",
        "theme.aria": "Toggle theme",
        "menu.aria": "Open navigation menu",
        "backTop.aria": "Back to top",
        "hero.badge": "Case Referral • Confidential Booking • Counselor Management",
        "hero.title": "Counseling <span class=\"gradient-text\">Referral System</span>",
        "hero.description": "One system for lecturer/staff case referrals, confidential student self-booking, and appointment management by TVETMARA Besut counselors.",
        "hero.primaryCta": "Submit Case Referral",
        "hero.secondaryCta": "Confidential Student Booking",
        "hero.statConfidential": "Lecturer / Staff Referral",
        "hero.statConfidentialText": "Refer student cases to the counseling unit",
        "hero.statResponse": "Confidential Self-Booking",
        "hero.statResponseText": "Students may request support without lecturer/staff notice",
        "hero.statOnline": "Counselor Dashboard",
        "hero.statOnlineText": "Manage cases, status, and session schedules",
        "hero.flowReferral": "Lecturer / Staff Referral",
        "hero.flowReferralText": "Refer student cases to the counseling unit",
        "hero.flowSelf": "Confidential Self-Booking",
        "hero.flowSelfText": "Students may request support without lecturer/staff notice",
        "hero.flowDashboard": "Counselor Dashboard",
        "hero.flowDashboardText": "Manage cases, status, and session schedules",
        "hero.referralKicker": "For Lecturer / Staff",
        "hero.referralCardTitle": "Submit Student Referral",
        "hero.referralCardDesc": "Refer students who need counseling support with referral reasons and supporting information.",
        "hero.selfKicker": "For Students",
        "hero.selfCardTitle": "Confidential Self-Booking",
        "hero.selfCardDesc": "Students may request a counseling session directly and confidentially without notifying other parties.",
        "hero.trustNote": "Information is confidential and only accessible by the Counseling and Career Unit.",
        "hero.brandCard": "Counseling and Career Unit",
        "hero.calendarMonth": "July 2026",
        "hero.availabilityTitle": "Appointment Slots",
        "hero.availabilityLoading": "Checking availability...",
        "hero.availabilityEmpty": "No nearby slots are available. Please check the booking section.",
        "hero.availableSlots": "{count} slots",
        "hero.viewAllSlots": "View All Slots",
        "hero.quote": "\"You do not have to figure everything out alone.\"",
        "hero.quoteBy": "- Counseling and Career Unit",
        "hero.quotes": [
            "\"You do not have to figure everything out alone.\"",
            "\"One small step today can create a calmer tomorrow.\"",
            "\"Asking for support is part of taking care of yourself.\""
        ],
        "counselors.subtitle": "Our Team",
        "counselors.title": "Counselors of the Counseling and Career Unit",
        "counselors.description": "Officers ready to listen, guide, and support TVETMARA Besut students throughout their learning and career journey.",
        "services.title": "Counseling Support Areas",
        "services.description": "Referrals and bookings may involve academic, career, emotional, and student welfare support.",
        "services.academicTitle": "Academic Support",
        "services.academicDesc": "Learning guidance, motivation, and academic stress management.",
        "services.careerTitle": "Career Guidance",
        "services.careerDesc": "Career planning, job opportunities, and personal development.",
        "services.emotionTitle": "Emotional Health",
        "services.emotionDesc": "Support for stress, emotions, self-confidence, and well-being.",
        "services.welfareTitle": "Student Welfare",
        "services.welfareDesc": "Welfare, financial, and personal student support.",
        "services.learnMore": "Learn more",
        "services.duration45": "45-60 minutes",
        "services.duration30": "30-45 minutes",
        "services.academicSuitable": "Learning concerns",
        "services.careerSuitable": "Career planning",
        "services.emotionSuitable": "Emotional support",
        "services.welfareSuitable": "Welfare concerns",
        "process.referralTitle": "Lecturer / Staff Referral",
        "process.referral1": "Submit referral",
        "process.referral2": "Counselor reviews",
        "process.referral3": "Session scheduled",
        "process.referral4": "Follow-up action",
        "process.selfTitle": "Confidential Self-Booking",
        "process.self1": "Enter details",
        "process.self2": "Choose slot",
        "process.self3": "Counselor confirms",
        "process.self4": "Session held",
        "serviceModal.close": "Close service information",
        "serviceModal.eyebrow": "Service",
        "serviceModal.duration": "Session duration",
        "serviceModal.suitable": "Suitable for",
        "serviceModal.focusTitle": "Session focus",
        "serviceModal.book": "Book this session",
        "serviceDetail.Academic.desc": "A session to help students manage academic challenges, study motivation, course adjustment, and learning pressure.",
        "serviceDetail.Academic.suitable": "Students facing learning, motivation, assignment, or academic adjustment concerns.",
        "serviceDetail.Academic.focus": ["Identify academic challenges", "Build realistic study strategies", "Plan follow-up steps with a counselor"],
        "serviceDetail.Career.desc": "A session to guide students in career decisions, internship planning, interview preparation, and pathways after graduation.",
        "serviceDetail.Career.suitable": "Students planning internships, employment, resumes, or career direction.",
        "serviceDetail.Career.focus": ["Explore interests and strengths", "Plan internship or employment pathways", "Review resume and interview preparation"],
        "serviceDetail.Personal.desc": "Early support for students facing stress, conflict, worry, self-confidence concerns, or daily emotional challenges.",
        "serviceDetail.Personal.suitable": "Students who need a safe space to talk and reorganize their situation.",
        "serviceDetail.Personal.focus": ["Listen and understand the student's situation", "Identify suitable support", "Build small steps toward well-being"],
        "serviceDetail.Financial.desc": "A session to discuss student welfare, financial matters, allowances, campus support, and suitable assistance referrals.",
        "serviceDetail.Financial.suitable": "Students who need guidance on welfare, finances, or campus support.",
        "serviceDetail.Financial.focus": ["Identify the main welfare concern", "Review suitable support channels", "Plan next actions or referrals"],
        "booking.subtitle": "Referral & Appointment",
        "booking.title": "Counseling Referral and Appointment Management System",
        "booking.description": "Start with a lecturer/staff referral or confidential self-booking. The calendar shows available slots based on the selected counselor.",
        "booking.step1": "1. Application Details",
        "booking.step2": "2. Choose Date & Time",
        "booking.guideTitle": "How to use the system",
        "booking.guideStep1": "Choose the application type: lecturer/staff referral or confidential student self-booking.",
        "booking.guideStep2": "Choose the counselor first so the calendar only shows that counselor's available slots.",
        "booking.guideStep3": "Counselors will review the case, decide individual or group session, and notify the student of the status.",
        "booking.slotTitle": "Choose Time Slot",
        "booking.selectDatePrompt": "Please select a valid date first.",
        "booking.chooseCounselorFirst": "Please choose your preferred counselor first to check available dates and slots.",
        "booking.noSelection": "No date/time selected yet.",
        "statusChecker.title": "Check Booking Status",
        "statusChecker.desc": "Enter your ticket reference and student ID to check whether your booking is pending, approved, cancelled, or rescheduled.",
        "statusChecker.ticket": "Ticket Reference",
        "statusChecker.ticketPlaceholder": "e.g. T-1234",
        "statusChecker.studentId": "Student ID",
        "statusChecker.studentIdPlaceholder": "e.g. DFK230717",
        "statusChecker.button": "Check Status",
        "statusChecker.notFound": "No booking found. Please check your ticket reference and student ID.",
        "statusChecker.foundTitle": "Your booking status",
        "statusChecker.note": "Please check this status from time to time. For the real system, automatic email/WhatsApp notifications can be connected after the database is built.",
        "statusChecker.status": "Status",
        "statusChecker.requestType": "Application Type",
        "statusChecker.dateTime": "Date & Time",
        "statusChecker.counselor": "Counselor",
        "statusChecker.type": "Session Type",
        "calendar.prev": "Previous month",
        "calendar.next": "Next month",
        "calendar.sun": "Sun",
        "calendar.mon": "Mon",
        "calendar.tue": "Tue",
        "calendar.wed": "Wed",
        "calendar.thu": "Thu",
        "calendar.fri": "Fri",
        "calendar.sat": "Sat",
        "calendar.available": "Available",
        "calendar.selected": "Selected",
        "calendar.unavailable": "Unavailable",
        "form.fullName": "Full Name <span class=\"required\">*</span>",
        "form.fullNamePlaceholder": "e.g. Aqilah Husna",
        "form.requestType": "Application Type",
        "form.requestSelf": "Confidential Self-Booking",
        "form.requestReferral": "Lecturer / Staff Referral",
        "form.referralFirstNote": "Lecturer/staff referral is the main flow. Students may still choose confidential self-booking.",
        "form.selfPrivacyNote": "Student self-booking is confidential. Lecturers, programme heads, or other staff will not be notified through this demo system.",
        "form.stepApplicant": "Type & applicant",
        "form.stepStudent": "Student details",
        "form.stepSession": "Session & slot",
        "form.stepSubmit": "Submit",
        "form.studentId": "Student ID <span class=\"required\">*</span>",
        "form.studentIdPlaceholder": "e.g. IKM240199",
        "form.preferredCounselor": "Preferred Counselor <span class=\"required\">*</span>",
        "form.program": "Program / Course <span class=\"required\">*</span>",
        "form.selectProgram": "Select program / course",
        "form.programPlaceholder": "e.g. Diploma Teknologi Maklumat",
        "form.semester": "Semester <span class=\"required\">*</span>",
        "form.selectSem": "Select Semester",
        "form.sem1": "Semester 1",
        "form.sem2": "Semester 2",
        "form.sem3": "Semester 3",
        "form.sem4": "Semester 4",
        "form.sem5": "Semester 5",
        "form.sem6": "Semester 6",
        "form.phone": "Phone Number <span class=\"required\">*</span>",
        "form.phonePlaceholder": "e.g. 0123456789",
        "form.sessionType": "Consultation Type <span class=\"required\">*</span>",
        "form.selectConcern": "Select concern area",
        "form.reason": "Briefly Describe Your Needs (Optional)",
        "form.reasonPlaceholder": "Briefly describe what you would like to discuss. Your information is confidential.",
        "form.referralInfo": "Referral Details",
        "form.referrerName": "Referrer Name <span class=\"required\">*</span>",
        "form.referrerNamePlaceholder": "e.g. Ms. Siti Aminah",
        "form.referrerPosition": "Referrer Position <span class=\"required\">*</span>",
        "form.referrerPositionPlaceholder": "e.g. Lecturer / HEP Officer / Warden",
        "form.referrerDepartment": "Department / Program <span class=\"required\">*</span>",
        "form.referrerDepartmentPlaceholder": "e.g. DFK / HEP / Hostel",
        "form.referralSource": "Referral Category <span class=\"required\">*</span>",
        "form.selectReferralSource": "Select referral category",
        "form.referralSessionMode": "Suggested Session Mode (Optional)",
        "form.selectSessionMode": "Select session mode",
        "form.counselorDecides": "Counselor decides",
        "form.referralPriority": "Priority Level <span class=\"required\">*</span>",
        "form.referralReason": "Referral Reason <span class=\"required\">*</span>",
        "form.referralReasonPlaceholder": "Briefly state the reason for referral.",
        "form.referralAttachment": "Supporting Attachment",
        "form.attachmentHint": "For this demo, only the attachment file name is stored.",
        "form.submit": "Submit Appointment Request",
        "sessionType.Academic": "Academic Counseling",
        "sessionType.Career": "Career & Employability Guidance",
        "sessionType.Personal": "Personal / Emotional Support",
        "sessionType.Financial": "Financial Assistance & Welfare",
        "sessionType.Other": "Other Counseling",
        "requestType.self": "Self",
        "requestType.referral": "Referral",
        "referralSource.Lecturer": "Lecturer Referral",
        "referralSource.HEP": "HEP Referral",
        "referralSource.Warden": "Warden Referral",
        "sessionMode.PendingDecision": "Counselor decides",
        "sessionMode.Individual": "Individual",
        "sessionMode.Group": "Group",
        "priority.Normal": "Normal",
        "priority.Urgent": "Urgent",
        "resources.subtitle": "Additional Support",
        "resources.title": "FAQs & Resources",
        "resources.description": "Quick information and early guidance for students before or after counseling sessions.",
        "faq.title": "Frequently Asked Questions",
        "faq.q1": "Is my information kept private?",
        "faq.a1": "Yes. Discussion topics, personal notes, and information shared during counseling remain confidential unless there is a safety risk to yourself or others.",
        "faq.q2": "How long is each session?",
        "faq.a2": "A session usually takes 45 to 60 minutes. The duration can be adjusted according to your needs and situation.",
        "faq.q3": "What should I do in an emergency?",
        "faq.a3": "If you or a friend is in immediate crisis, contact campus wardens, call Talian Kasih at 15999, or come directly to the Counseling and Career Unit during office hours.",
        "resources.guidesTitle": "Mental Health & TVET Guides",
        "resources.stressTitle": "Stress Management Guide for TVET Students",
        "resources.stressDesc": "Simple techniques to balance workshops, assignments, and academics.",
        "resources.careerTitle": "Career Preparation Checklist",
        "resources.careerDesc": "Prepare your resume, interview practice, and internship search.",
        "resources.mindTitle": "10-Minute Breathing Practice",
        "resources.mindDesc": "A simple practice to calm yourself before assessments or presentations.",
        "dashboard.title": "Counselor Case Management Dashboard",
        "dashboard.subtitle": "Review referrals, approve appointments, decide individual/group sessions, and manage your own availability.",
        "dashboard.adminMode": "COUNSELOR ACCOUNT",
        "dashboard.exit": "Exit Portal",
        "dashboard.total": "Total Bookings",
        "dashboard.pending": "Pending Review",
        "dashboard.approved": "Approved Appointments",
        "dashboard.referralCases": "Referral Cases",
        "dashboard.selfBookings": "Private Bookings",
        "dashboard.appointments": "Appointment List",
        "dashboard.generalAppointments": "General Student Booking List",
        "dashboard.generalAppointmentsDesc": "A brief shared view of all bookings. Actions remain available only in your own appointment list.",
        "dashboard.allStatus": "All Statuses",
        "dashboard.newBookingAlert": "{count} new / pending booking(s) need your review.",
        "dashboard.noNewBookingAlert": "No new pending bookings need review right now.",
        "dashboard.downloadTitle": "Download booking data",
        "dashboard.downloadDesc": "Save a CSV copy of booking data for unit records.",
        "dashboard.sessionDecision": "Session decision",
        "download.myClients": "Download My Clients",
        "download.allBookings": "Download All Bookings",
        "download.empty": "No booking data available to download.",
        "availability.title": "Counselor Availability",
        "availability.description": "Manage your own dates and time slots. Students will only see the session times you open.",
        "availability.counselor": "Counselor",
        "availability.minNotice": "Minimum Notice Before Session (hours)",
        "availability.minNoticeHint": "Example: 24 hours means students cannot make a sudden booking this morning for a same-day session.",
        "availability.prev": "Previous month",
        "availability.next": "Next month",
        "availability.available": "Available",
        "availability.unavailable": "Unavailable",
        "availability.saved": "Availability settings saved.",
        "availability.noCounselor": "Please add a counselor before setting availability.",
        "availability.profileTitle": "Signed-in account",
        "availability.slotTitle": "Time slots for selected date",
        "availability.selectDate": "Click a date on the calendar to manage time slots.",
        "availability.noDate": "No date selected",
        "availability.openAll": "Open all slots",
        "availability.closeAll": "Close all slots",
        "availability.defaultSlots": "All slots are open by default.",
        "availability.visibleToStudents": "This slot is visible to students.",
        "availability.tooSoon": "This slot is open, but students cannot book it yet because of the minimum notice.",
        "availability.bookedSlot": "This slot already has an approved appointment.",
        "availability.closedSlot": "This slot is closed by the counselor.",
        "availability.openShort": "Open",
        "availability.tooSoonShort": "Too soon",
        "availability.bookedShort": "Booked",
        "availability.closedShort": "Closed",
        "booking.noSlots": "No slots are available for this date. Please choose another date or counselor.",
        "table.dateTime": "Date & Time",
        "table.student": "Student Details",
        "table.counselor": "Counselor",
        "table.typeReason": "Type & Reason",
        "table.status": "Status",
        "table.actions": "Actions",
        "directory.title": "Counselor Directory Management",
        "directory.active": "Active Counselors / Interns",
        "directory.addProfile": "Add New Profile",
        "directory.fullName": "Full Name <span class=\"required\">*</span>",
        "directory.fullNamePlaceholder": "e.g. Cik Nor Shazwani binti Rosli",
        "directory.role": "Role / Credentials <span class=\"required\">*</span>",
        "directory.rolePlaceholder": "e.g. Registered Intern Counselor (KB, PA)",
        "directory.badge": "Badge Label <span class=\"required\">*</span>",
        "directory.badgePlaceholder": "e.g. Intern Counselor",
        "directory.specialties": "Specialties (comma separated) <span class=\"required\">*</span>",
        "directory.specialtiesPlaceholder": "e.g. Exam Stress, Study Motivation, Career Path",
        "directory.scopes": "Job Scopes / Services (comma separated) <span class=\"required\">*</span>",
        "directory.scopesPlaceholder": "e.g. Individual Counseling, Group Counseling, Academic Support",
        "directory.bio": "Brief Biography <span class=\"required\">*</span>",
        "directory.bioPlaceholder": "Describe counselor credentials, specialization areas, and background...",
        "directory.submit": "Add Counselor Profile",
        "modal.successTitle": "Appointment Request Submitted",
        "modal.successDesc": "Thank you. Your request has been recorded and is pending counselor approval. Session details are below:",
        "modal.done": "Done",
        "modal.print": "Print Ticket",
        "receipt.ticket": "Ticket Reference:",
        "receipt.student": "Student Name:",
        "receipt.dateTime": "Date & Time:",
        "receipt.counselor": "Assigned Counselor:",
        "receipt.type": "Consultation Type:",
        "receipt.statusNote": "Status: Pending review. In certain circumstances, the session may be transferred to another counselor and you will be informed.",
        "receipt.saveReminder": "Please save this receipt or take a screenshot. Use the ticket number to check whether your booking is pending, approved, cancelled, or transferred to another counselor.",
        "auth.title": "Counselor Portal Authentication",
        "auth.desc": "Choose your counselor account and enter your password to manage your own appointments and availability.",
        "auth.chooseAccount": "Choose counselor account",
        "auth.password": "Password",
        "auth.placeholder": "Enter account password",
        "auth.error": "Invalid password. Please try again.",
        "auth.cancel": "Cancel",
        "auth.signIn": "Sign In",
        "auth.showPassword": "Show password",
        "auth.hidePassword": "Hide password",
        "footer.brand": "Counseling and Career Unit",
        "footer.desc": "Confidential, professional, and student-friendly counseling and career guidance services for TVETMARA Besut.",
        "footer.hoursTitle": "Office Hours",
        "footer.hours1": "Sunday - Wednesday: 8:00 AM - 5:00 PM",
        "footer.hours2": "Thursday: 8:00 AM - 3:30 PM",
        "footer.hours3": "Friday - Saturday: Closed",
        "footer.contactTitle": "Contact Us",
        "footer.address": "Counseling and Career Unit, IKM Besut",
        "footer.copy": "&copy; 2026 Counseling and Career Unit, TVETMARA Besut. All rights reserved.",
        "status.Pending": "Pending",
        "status.Approved": "Approved",
        "status.Cancelled": "Cancelled",
        "select.chooseCounselor": "Choose a counselor",
        "select.allCounselors": "All Counselors",
        "counselor.noActiveTitle": "No active counselors currently available",
        "counselor.noActiveDesc": "Please check back later or contact the administration unit.",
        "counselor.bookSession": "Book Session",
        "directory.noActive": "No active counselors registered.",
        "directory.deleteTitle": "Delete Counselor Profile",
        "directory.deleteConfirm": "Are you sure you want to delete {name}? This will remove them from the counselor directory and slot scheduling selection.",
        "alerts.requiredFields": "Please fill in all required fields.",
        "alerts.profileAdded": "Profile for {name} has been added successfully.",
        "alerts.selectDate": "Please select a date and an available time slot.",
        "alerts.resourceStress": "Demo Resource: Opening stress management guide.",
        "alerts.resourceCareer": "Demo Resource: Opening career checklist.",
        "alerts.resourceMindfulness": "Demo Resource: Opening breathing practice.",
        "summary.selected": "Selected:",
        "summary.at": "at",
        "booking.unassigned": "Unassigned",
        "table.noAppointments": "No appointments matching the selected filters found.",
        "table.noGeneralAppointments": "No student bookings are available yet.",
        "table.ref": "Ref",
        "table.referrer": "Referrer",
        "table.unit": "Counseling and Career Unit",
        "table.noDetails": "No details provided",
        "action.approve": "Approve booking",
        "action.cancelDecline": "Cancel / decline booking",
        "action.reschedule": "Request student reschedule",
        "action.cancel": "Cancel booking",
        "action.reopen": "Reopen / set to pending",
        "action.transfer": "Transfer to another counselor",
        "action.whatsapp": "Send WhatsApp notice",
        "reschedule.prompt": "Reschedule booking Ref: {ref} for {name}.\nEnter new date (DD/MM/YY or DD/MM/YYYY):",
        "reschedule.timePrompt": "Enter new time. Options: {slots}",
        "reschedule.invalidDate": "Invalid date format. Use DD/MM/YY or DD/MM/YYYY.",
        "reschedule.invalidTime": "Invalid time. Please choose one of the available slots.",
        "reschedule.success": "Rescheduled successfully. Status reverted to pending for review. Students can check changes with their ticket reference in the Check Booking Status section.",
        "transfer.prompt": "Transfer booking Ref: {ref} to another counselor.\nOptions:\n{options}\n\nEnter option number:",
        "transfer.invalid": "Invalid counselor option.",
        "transfer.success": "Booking transferred and set to pending for the receiving counselor's review.",
        "whatsapp.message": "Assalamualaikum {name}. Your counseling booking ({ref}) status is: {status}. Date/Time: {date} {time}. Counselor: {counselor}. Please keep this ticket number to check your status on the TVETMARA Besut Counseling and Career Unit website.",
        "whatsapp.noPhone": "Student phone number is not available.",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    }
};

// Pre-populated default counselors
const DEFAULT_COUNSELORS = [
    {
        id: "c1",
        name: "EN SOLAHUDIN",
        role: "Kaunselor Berdaftar (KB, PA)",
        badge: "Kaunselor",
        photo: "images/Solahudin.png",
        specialties: ["Bimbingan Akademik", "Hala Tuju Kerjaya", "Sokongan Emosi"],
        bio: "Memberi tumpuan kepada bimbingan kerjaya, motivasi pembelajaran dan sokongan emosi untuk membantu pelajar TVET berkembang secara seimbang."
    },
    {
        id: "c2",
        name: "PUAN NOOR AZILA",
        role: "Advokasi Kesihatan Mental & Bimbingan Pelajar",
        badge: "Kaunselor",
        photo: "images/puan.png",
        specialties: ["Pengurusan Stres", "Keyakinan Diri", "Konflik Keluarga"],
        bio: "Berpengalaman dalam persekitaran TVET dengan fokus kepada pengurusan konflik peribadi, stres, kebimbangan dan sokongan keluarga."
    }
];

const COUNSELOR_ACCOUNTS = [
    {
        counselorId: "c1",
        password: "solahudin123"
    },
    {
        counselorId: "c2",
        password: "azila123"
    }
];

// Pre-populated demo appointments for a realistic experience
const DEMO_APPOINTMENTS = [
    {
        id: "1720315000000",
        ticketRef: "T-8941",
        studentName: "Muhammad Aqil bin Roslan",
        studentId: "IKM241104",
        studentProgram: "DCG - DIPLOMA KOMPETENSI ELEKTRIK",
        studentSem: "Sem 3",
        studentPhone: "013-9876543",
        counselorName: "EN SOLAHUDIN",
        sessionType: "Career",
        sessionReason: "Ingin berbincang tentang pilihan latihan industri di kawasan Terengganu dan keperluan penempatan.",
        dateStr: "2026-07-08",
        timeSlot: "10:00 AM",
        status: "Approved"
    },
    {
        id: "1720316000000",
        ticketRef: "T-3210",
        studentName: "Nurul Farhana binti Mohamad",
        studentId: "IKM250109",
        studentProgram: "ITW - DIPLOMA KOMPETENSI KIMPALAN",
        studentSem: "Sem 1",
        studentPhone: "019-2345678",
        counselorName: "PUAN NOOR AZILA",
        sessionType: "Personal",
        sessionReason: "Berasa tertekan dengan persediaan penilaian bengkel dan pengurusan masa.",
        requestType: "referral",
        referralSource: "Lecturer",
        referrerName: "Pn. Siti Aminah",
        referrerPosition: "Pensyarah Program",
        referrerDepartment: "ITW",
        referralReason: "Pelajar kelihatan tertekan dan memerlukan sokongan awal berkaitan penyesuaian pembelajaran.",
        referralSessionMode: "PendingDecision",
        referralPriority: "Normal",
        referralAttachmentName: "",
        dateStr: "2026-07-08",
        timeSlot: "02:00 PM",
        status: "Pending"
    },
    {
        id: "1720317000000",
        ticketRef: "T-7729",
        studentName: "Ahmad Danish bin Zulkifli",
        studentId: "IKM240212",
        studentProgram: "DGA - DIPLOMA TEKNOLOGI AUTOMOTIF",
        studentSem: "Sem 4",
        studentPhone: "011-5544332",
        counselorName: "EN SOLAHUDIN",
        sessionType: "Academic",
        sessionReason: "Ingin mendapatkan nasihat berkaitan pemindahan kredit dan perancangan semester seterusnya.",
        dateStr: "2026-07-09",
        timeSlot: "11:00 AM",
        status: "Pending"
    },
    {
        id: "1720318000000",
        ticketRef: "T-5512",
        studentName: "Siti Sarah binti Abdullah",
        studentId: "IKM230302",
        studentProgram: "DFK - DIPLOMA TEKNOLOGI KOMPUTER (KOMPUTASI AWAN)",
        studentSem: "Sem 6",
        studentPhone: "017-8899221",
        counselorName: "PUAN NOOR AZILA",
        sessionType: "Financial",
        sessionReason: "Konsultasi berkaitan kebajikan pelajar dan kelewatan elaun MARA.",
        dateStr: "2026-07-06",
        timeSlot: "09:00 AM",
        status: "Cancelled"
    }
];
